apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lime
      link: monolithic
  template:
    metadata:
      labels:
        app: lime
        link: monolithic
    spec:
      containers:
      - name: app-backend
        # image: 039754395781.dkr.ecr.us-east-1.amazonaws.com/munjiz/backend:v0.0.7
        image: local/app:1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: '/'
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 40
          failureThreshold: 60
        readinessProbe:
          httpGet:
            path: '/'
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 40
          failureThreshold: 60
        ports:
        - name: app-port
          containerPort: 8080
          protocol: TCP
        envFrom:
          - configMapRef:
              name: app-backend-config
        # resources:
        #     requests:
        #       memory: '2Gi'
        #       cpu: '500m'
        #     limits:
        #       memory: '2Gi'
        #       cpu: '500m'