apiVersion: v1
kind: Service
metadata:
  name: iam-db
  namespace: dev
  # this label has no impact so far
  labels:
    app: keyclock
spec:
  # this maps to deployment label
  selector:
    app: keyclock
  ports:
  - protocol: TCP
    port: 5432
    targetPort: iam-db-port
  type: LoadBalancer