apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: dev
  labels:
    type: local
    app: keyclock
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: dev
  labels:
    type: local
    app: keyclock
spec:
  selector:
    matchLabels:
      app: keyclock
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi