version: "3.9"
services:
  backend.notification.local:
    container_name: app-backend
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      # below line for development purposes only. Enabling developer to see changes instantely without the need to rebuild
      - .:/app
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./devops/app-backend/app.env
    restart: always
    depends_on:
      - backend.db.notification.local
  backend.db.notification.local:
    container_name: app-db
    image: postgres:13-alpine
    volumes:
      - app_db:/var/lib/postgresql/data/
    env_file:
      - devops/app-backend/db.env
    ports:
      - "5432:5432"
  # app-xray.notification.local:
  #   container_name: aws-xray
  #   build: ./devops/xray
  #   command: --local-mode
  #   env_file:
  #     - ./devops/xray/xray.env
  #   ports:
  #     - "2000:2000/udp"
  #   links:
  #     - backend.notification.local
  iam.notifications.local:
    container_name: iam-backend
    build: devops/keycloak
    restart: always
    env_file:
      - ./devops/keycloak/iam.env
    ports:
      - '8443:8443'
      - '8080:8080'
    command:
      - start-dev
    depends_on:
      - iam.db.notification.local
  iam.db.notification.local:
    container_name: iam-db
    image: postgres:13-alpine
    volumes:
      - iam_db:/var/lib/postgresql/data/
    env_file:
      - devops/keycloak/iam-db.env
    ports:
      - "5430:5432"

networks:
  default:
    name: app_custom_network

volumes:
  app_db:
  iam_db: